server:
  port: 8888

spring:
  application:
    name: config-server
  security:
    user:
      name: luciocarlos
      password: luciocarlos2002
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Luciocarlos2002/config-repo
          search-paths: /
          default-label: "dev"
